apiVersion: v1
kind: Service
metadata:
  name: nginx-dep-lb
  labels:
    app: nginx-dep
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-dep
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort                   
  selector:
    app: nginx-dep
  ports:
    - protocol: TCP
      port: 80                  
      targetPort: 80   
      nodePort: 30080 # 외부 포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-dep
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: nginx-dep
  template:
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
      - name: nginx-dep
        image: nginx:1.14.2
        ports:
        - containerPort: 80  
